import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
import { Eye, AlertTriangle, CheckCircle, Globe, FileText, Server } from "lucide-react";
const DEMO_TOKENS = [
    { id: "tok_001", type: "file", description: "passwords_backup.txt", triggered: true, trigger_count: 2, path: "C:\\Users\\HP\\Desktop\\" },
    { id: "tok_002", type: "file", description: "vpn_credentials.json", triggered: false, trigger_count: 0, path: "C:\\Users\\HP\\Documents\\" },
    { id: "tok_003", type: "file", description: "database_config.env", triggered: false, trigger_count: 0, path: "C:\\Users\\HP\\Desktop\\" },
    { id: "tok_004", type: "file", description: "aws_credentials", triggered: false, trigger_count: 0, path: "C:\\Users\\HP\\.aws\\" },
    { id: "tok_005", type: "port", description: "Port 4444/tcp (Meterpreter leurre)", triggered: true, trigger_count: 1, path: "0.0.0.0:4444" },
    { id: "tok_006", type: "port", description: "Port 1337/tcp (Hacker classic)", triggered: false, trigger_count: 0, path: "0.0.0.0:1337" },
    { id: "tok_007", type: "port", description: "Port 31337/tcp (Elite port)", triggered: false, trigger_count: 0, path: "0.0.0.0:31337" },
];
const TYPE_ICON = {
    file: _jsx(FileText, { className: "w-3 h-3" }),
    port: _jsx(Globe, { className: "w-3 h-3" }),
    process: _jsx(Server, { className: "w-3 h-3" }),
};
export default function DeceptionStatus({ alerts }) {
    const honeyAlerts = useMemo(() => alerts.filter((a) => a.type === "HONEYTOKEN_TRIGGERED"), [alerts]);
    const triggered = DEMO_TOKENS.filter((t) => t.triggered);
    const safe = DEMO_TOKENS.filter((t) => !t.triggered);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "grid grid-cols-3 gap-4", children: [_jsxs("div", { className: "bg-gray-900 rounded-xl border border-gray-800 p-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-gray-400 text-xs mb-2", children: [_jsx(Eye, { className: "w-4 h-4 text-orange-400" }), " Honeytokens d\u00E9ploy\u00E9s"] }), _jsx("div", { className: "text-3xl font-bold text-white", children: DEMO_TOKENS.length })] }), _jsxs("div", { className: `bg-gray-900 rounded-xl border p-4 ${triggered.length > 0 ? "border-red-500/50" : "border-gray-800"}`, children: [_jsxs("div", { className: "flex items-center gap-2 text-gray-400 text-xs mb-2", children: [_jsx(AlertTriangle, { className: "w-4 h-4 text-red-400" }), " D\u00E9clench\u00E9s"] }), _jsx("div", { className: `text-3xl font-bold ${triggered.length > 0 ? "text-red-400" : "text-white"}`, children: triggered.length }), triggered.length > 0 && _jsx("div", { className: "text-xs text-red-400 mt-1 animate-pulse", children: "Attaquant d\u00E9tect\u00E9 !" })] }), _jsxs("div", { className: "bg-gray-900 rounded-xl border border-gray-800 p-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-gray-400 text-xs mb-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-emerald-400" }), " Intacts"] }), _jsx("div", { className: "text-3xl font-bold text-emerald-400", children: safe.length })] })] }), honeyAlerts.length > 0 && (_jsxs("div", { className: "bg-red-500/10 border border-red-500/40 rounded-xl p-4", children: [_jsxs("h3", { className: "text-sm font-semibold text-red-300 mb-3 flex items-center gap-2", children: [_jsx(AlertTriangle, { className: "w-4 h-4" }), " Incidents de d\u00E9ception confirm\u00E9s"] }), honeyAlerts.map((alert, i) => (_jsxs("div", { className: "text-xs text-red-200 bg-red-500/10 rounded-lg p-2 mb-2", children: [_jsx("p", { className: "font-semibold", children: alert.reason }), _jsx("p", { className: "text-red-400 mt-1", children: alert.received_at?.slice(0, 19) })] }, i)))] })), _jsxs("div", { className: "bg-gray-900 rounded-xl border border-gray-800 p-4", children: [_jsxs("h3", { className: "text-sm font-semibold uppercase tracking-wider text-gray-400 mb-4 flex items-center gap-2", children: [_jsx(Eye, { className: "w-4 h-4 text-orange-400" }), " Carte des Honeytokens"] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3", children: DEMO_TOKENS.map((token) => (_jsxs("div", { className: `rounded-lg border p-3 ${token.triggered
                                ? "border-red-500/50 bg-red-500/10"
                                : "border-gray-700 bg-gray-800/50"}`, children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("span", { className: token.triggered ? "text-red-400" : "text-gray-500", children: TYPE_ICON[token.type] || _jsx(Eye, { className: "w-3 h-3" }) }), _jsx("span", { className: "text-xs font-mono text-gray-400 uppercase", children: token.type }), token.triggered ? (_jsx("span", { className: "ml-auto text-xs bg-red-500/20 text-red-300 px-1.5 rounded animate-pulse", children: "\u26A0 D\u00C9CLENCH\u00C9" })) : (_jsx("span", { className: "ml-auto text-xs bg-emerald-500/20 text-emerald-400 px-1.5 rounded", children: "\u2713 Actif" }))] }), _jsx("div", { className: "text-sm font-medium text-white", children: token.description }), _jsx("div", { className: "text-xs text-gray-600 mt-1 font-mono truncate", children: token.path }), token.triggered && (_jsxs("div", { className: "text-xs text-red-400 mt-2", children: [token.trigger_count, " d\u00E9clenchement", token.trigger_count > 1 ? "s" : ""] }))] }, token.id))) })] }), _jsxs("div", { className: "bg-gray-900 rounded-xl border border-gray-800 p-4", children: [_jsxs("h3", { className: "text-sm font-semibold text-gray-400 mb-3 flex items-center gap-2", children: [_jsx(Eye, { className: "w-4 h-4 text-purple-400" }), " Comment fonctionne la Deception Engine"] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs text-gray-500", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("div", { className: "text-gray-300 font-semibold", children: "1. D\u00E9ploiement" }), _jsx("p", { children: "Des fichiers, ports et ressources leurres sont d\u00E9ploy\u00E9s sur toutes les machines prot\u00E9g\u00E9es." })] }), _jsxs("div", { className: "space-y-1", children: [_jsx("div", { className: "text-gray-300 font-semibold", children: "2. Attente passive" }), _jsx("p", { children: "Aucun utilisateur l\u00E9gitime n'a de raison d'acc\u00E9der \u00E0 ces ressources. Toute interaction = attaquant." })] }), _jsxs("div", { className: "space-y-1", children: [_jsx("div", { className: "text-gray-300 font-semibold", children: "3. Alerte certaine" }), _jsx("p", { children: "Un honeytoken d\u00E9clench\u00E9 = 100% de certitude d'un incident. Collecte forensics automatique." })] })] })] })] }));
}
